# Generated by Django 4.1.3 on 2022-12-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cve_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SingleCve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cve", models.CharField(max_length=30, unique=True)),
                ("cve_data", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="cvedetails",
            name="cve_data",
        ),
    ]
