# Generated by Django 4.1.3 on 2022-12-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cve_app", "0002_singlecve_remove_cvedetails_cve_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvedetails",
            name="cve_id",
            field=models.CharField(max_length=30),
        ),
    ]
